"""LLM client wrapper -- deterministic mock for perception/generation steps.

All artifact content is generated by stage agents via domain templates or tools.
LLMClient returns structured placeholders to keep the call chain working,
with no dependency on external APIs.
"""
from __future__ import annotations

from dataclasses import dataclass


@dataclass
class LLMResponse:
    text: str
    model: str


class LLMClient:
    """Deterministic mock LLM client."""

    def __init__(self) -> None:
        self.mode = "mock"
        self.model = "mock"

    def complete(self, system: str, prompt: str, max_tokens: int = 4096,
                 temperature: float = 0.2) -> LLMResponse:
        head = prompt.strip().splitlines()[0] if prompt.strip() else ""
        return LLMResponse(
            text=f"[MOCK] ack: {head[:80]}",
            model=self.model,
        )
